/* Generated by CMunge 0.78 (17 Dec 2021)
 * CMunge Copyright (c) 1999-2006 Robin Watts/Justin Fletcher */

#ifndef ImageFileRender_SWI_H
#define ImageFileRender_SWI_H

/* SWI numbers */
#define ImageFileRender_Render  0x562c0
#define ImageFileRender_BBox    0x562c1
#define ImageFileRender_Transform 0x562c2
#define ImageFileRender_DeclareFonts 0x562c3
#define ImageFileRender_Info    0x562c4
#define ImageFileRender_RendererInfo 0x562c5
#define ImageFileRender_Register 0x562c6
#define ImageFileRender_Deregister 0x562c7
#define ImageFileRender_EnumerateRenderers 0x562c8

#endif

